### ISSUE TITLE
Project Checklist

### ISSUE THREAD

**Issue by Challenger-84** [Challenger-84/cs_project#3]
- [ ] Add cart page
- [ ] Add discount option
- [ ] Make user review system
- [ ] Add comments
- [ ] Make checkout page
